version: "2"
services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./conf.d/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on: 
            - php

    php:
        build:
          context: ./php-fpm
        restart: always
        volumes:
            - ./code:/code
            - ./html:/var/www/html
        networks:
            - code-network
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
            MYSQL_USER: "mysuser"
            MYSQL_PASSWORD: "mypass"
            MYSQL_DATABASE: "awesomedb"
            MYSQL_PORT : 3306
        depends_on: 
            - db

    db:
        image: mariadb:latest
        restart: always
        ports:
            - "3306:3306"
        networks: 
            - code-network
        volumes: 
            - db-data:/var/lib/mysql
        expose: 
            - '3306'
        environment: 
            MYSQL_ROOT_PASSWORD: "rootPass"
            MYSQL_USER: "mysuser"
            MYSQL_PASSWORD: "mypass"
            MYSQL_DATABASE: "awesomedb"

networks:
    code-network:
        driver: bridge

volumes: 
    db-data: