version: "3"
services:
    php:
        build:
          context: ./php-fpm
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./code:/code
            - ./log:/var/www/html
        networks:
            - code-network
        environment:
            MYSQL_USER: "mysuser"
            MYSQL_PASSWORD: "mypass"
            MYSQL_DATABASE: "awesomedb"
            MYSQL_PORT : 3306
        depends_on: 
            - db

    db:
        image: mariadb:latest
        restart: always
        ports:
            - "3306:3306"
        networks: 
            - code-network
        volumes: 
            - db-data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: "rootPass"
            MYSQL_USER: "mysuser"
            MYSQL_PASSWORD: "mypass"
            MYSQL_DATABASE: "awesomedb"

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        networks: 
            - code-network
        volumes: 
            - redis-data:/data

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - "8088:8080"
        networks: 
            - code-network

networks:
    code-network:
        driver: bridge

volumes: 
    db-data:
    redis-data: