version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.4.0
        restart: always
        ports:
            - "9200:9200"
            - "9300:9300"
        networks: 
            - management-network
        environment: 
            - discovery.type=single-node
            - xpack.security.enabled=false
        volumes: 
            - elasticsearch-data:/usr/share/elasticsearch/data
    
    kibana:
        image: kibana:7.4.0
        restart: always
        ports:
            - "5601:5601"
        networks: 
            - management-network
        depends_on:
            - logstash

    logstash:
        image: logstash:7.4.0
        depends_on:
            - elasticsearch
        ports:
            - 12201:12201/udp
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        networks:
            - management-network

    portainer:
        image: portainer/portainer
        restart: always
        ports:
            - "9000:9000"
            - "8000:8000"
        networks: 
            - management-network
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

networks:
    management-network:
        driver: bridge

volumes: 
    elasticsearch-data:
    portainer_data: